---

- name: Install Terraform in hosts
  hosts: host1
  become: true
  tasks:
    - name: Install unzip
      package:
        name: unzip


    - name: Install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root 
