---

- name: Playbook to update index and install packages
  hosts: all
  become: true
  tasks:
  - name: Install apache and php packages
    tags: always
    package:
      name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"  
      state: latest
      update_cache: yes

  - name: Copy files from controller to host
    copy:
      src: test.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    
