---

- name: Playbook to install httpd
  hosts: all
  become: true
  tasks:
  - name: Update yum
    yum:
      update_cache: yes
    
  - name: Remove httpd
    yum:
      name: httpd
      state: absent
