---

- name: Playbook to uninstall packages
  hosts: all
  become: true
  tasks:
  - name: Update cache and remove packages
    package:
      name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
      update_cache: yes
      state: absent
