- name: Install apache and php packages
  tags: always
  yum:
    name: 
      - "{{ apache_package_name}}"
      - "{{ php_package_name}}"
    state: latest
    update_cache: yes

- name: Change config file
  lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin praj@wlu.com
  notify: apache_handler

- name: Start httpd
  service: 
    name: "{{apache_service_name}}"
    state: started
    enabled: yes

- name: Copy files from controller to host
  copy:
    src: test.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
